/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
 
/**
 *
 * @author Abhinav
 */
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.util.Scanner;

import javax.swing.*;
public class NewJFrame extends javax.swing.JFrame implements KeyListener {
 
	private Game g;
	private int target;
	String gameMode;
	javax.swing.JButton undo;
	javax.swing.JButton lookahead;
    javax.swing.JButton resetLookahead;
    javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField11;
    javax.swing.JTextField jTextField12;
    javax.swing.JTextField jTextField13;
    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
//        jPanel1.setLayout(new GridLayout(4,4));
    }
    public NewJFrame(int n,Game g,int target,String s){
        this.n=n;
        this.g=g;
        this.target=target;
        gameMode=s;
        initComponents();
        
    }

    public void display(int board[][]){
        for(int i=0;i<n;i++){
            for(int j=0;j<n;j++){
                arr[i*n+j].setText(Integer.toString(board[i][j]));
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {
    	addKeyListener(this);
    	setFocusable(true);
    	
        jPanel1 = new javax.swing.JPanel();
        jPanel1.setLayout(new java.awt.GridLayout(n,n));
        arr=new JTextField[n*n];
        for(int i=0;i<n*n;i++) {
        	arr[i]=new JTextField();
        	arr[i].setText("0");
        	arr[i].setEditable(false);
        	jPanel1.add(arr[i]);
        }
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
 
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        undo = new javax.swing.JButton();
        lookahead = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        resetLookahead = new javax.swing.JButton();
 
        undo.setFocusable(false);
    	lookahead.setFocusable(false);
    	resetLookahead.setFocusable(false);
 
        jLabel1.setText("Current Game Mode is:");

        jLabel2.setText("Target is:");
        
        jTextField11.setText(target+"");
        jTextField1.setText(gameMode);
        jTextField1.setEditable(false);
        jTextField11.setEditable(false);
        undo.setText("UNDO");
        undo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                undoActionPerformed(evt);
            }
        });

        lookahead.setText("LOOKAHEAD");
        lookahead.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lookaheadActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "UP", "DOWN", "LEFT", "RIGHT" }));

        resetLookahead.setText("RESET LOOKAHEAD");
        resetLookahead.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetLookaheadActionPerformed(evt);
            }
        });

        jLabel3.setText("Last Move:");

        jLabel4.setText("SumOfTiles:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 34, Short.MAX_VALUE)
                        .addComponent(resetLookahead)
                        .addGap(310, 310, 310))))
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(undo)
                        .addGap(42, 42, 42)
                        .addComponent(lookahead)
                        .addGap(76, 76, 76)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                            .addComponent(jTextField11)
                            .addComponent(jTextField12)
                            .addComponent(jTextField13))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(undo)
                    .addComponent(lookahead)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addComponent(resetLookahead)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void undoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_undoActionPerformed
        // TODO add your handling code here:
    	g.undo();
    }//GEN-LAST:event_undoActionPerformed

    private void lookaheadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lookaheadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lookaheadActionPerformed

    private void resetLookaheadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetLookaheadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resetLookaheadActionPerformed
    // Variables declaration - do not modify                     
    private javax.swing.JPanel jPanel1;
//    int[] intArray = new int[20];
    private JTextField[] arr;
    private static int n;
    /** Handle the key typed event from the text field. */
    public void keyTyped(KeyEvent e) {
//        System.out.println("KEY TYPED: "+e);
    }

    /** Handle the key-pressed event from the text field. */
    public void keyPressed(KeyEvent e) {
//    	System.out.println("key pressed "+e.getKeyCode());
        if(KeyEvent.getKeyText(e.getKeyCode())=="Left") {
        	g.move(MoveDirection.LEFT,true);
        }
        else if(KeyEvent.getKeyText(e.getKeyCode())=="Right") {
        	g.move(MoveDirection.RIGHT,true);
        }
        else if(KeyEvent.getKeyText(e.getKeyCode())=="Down") {
        	g.move(MoveDirection.DOWN,true);
        }
        else if(KeyEvent.getKeyText(e.getKeyCode())=="Up") {
        	g.move(MoveDirection.UP,true);
        }
    }

    /** Handle the key-released event from the text field. */
    public void keyReleased(KeyEvent e) {
//        System.out.println("KEY RELEASED: "+e);
    }
 
    // End of variables declaration                   
}
